/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Baskar' at '29/9/17 1:24 AM' with Gradle 2.14.1
 *
 * @author Baskar, @date 29/9/17 1:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
